#include "standalone.h"

/* ***** STANDALONE Implementation of a Network Compression Detector *****
	Implementation is based on this paper -> https://www.cs.usfca.edu/vahab/resources/compression_detection.pdf
	
	This program detects whether or not packets are being compressed on a network between two hosts
	by sending two packets trains, one with low entropy data and one with high entropy data. By bookending each of
	these packet trains with a TCP SYN head and TCP SYN tail packet over a raw socket, we can 
	capture the TCP RST packets generated by the server and save their timestamps. We then have the difference
	between the head and tail packets from the low entropy and high entropy packet trains -> The last step
	is to compare the differences between these two times, and see if it is greater than the threshold outlined 
	in the paper. If so, then compression occurs on the network. Otherwise, compression does not occur on the network.

	To run this program:
	sudo ./compdetect [config_file]

	*** NEED ROOT PRIVILEGES TO USE RAW SOCKETS ***
	
 */

struct arg_struct args[512];

int main(int argc, char *argv[]) {
	// Handle input
	if (argc != 2) {
		printf("Usage: ./compdetect_client [file_name]\n");
		exit(-1);
	}
	
	struct config_details config;	// Initialize config struct
	char file_contents[MAX_CONFIG_SIZE];		// Initialize buffer for config.json file contents

	// Parse config.json file (argv[1]), and populate config struct
	// Fill file_contents with config.json contents
	read_config_from_file(argv[1], &config, file_contents);	

	printf("About to create and send head SYN packet...\n");
	// Send the first packet train, with high_ent flag set to 0 so it sends low entropy data
	long low_ent = packet_train(config, 0);
	printf("First difference: %lu ms\n", low_ent);
	if (args->difference == 0) {
		printf("Failed to detect due to insufficient information\n");
		exit(-1);
	}

	sleep(atoi(config.inter_measurement_time));
	
	// Send the second packet train, this time with the high_ent flag set
	long high_ent = packet_train(config, 1);
	printf("Second difference: %lu ms\n", high_ent);
	if (args->difference == 0) {
	printf("Failed to detect due to insufficient information\n");
	exit(-1);
	}

	// Get difference between the packet train timestamps, and convert it from microseconds to milliseconds
	long overall_diff = (low_ent - high_ent);
	// Check if the difference is negative - If so, multiply by -1 to make it positive
	if (overall_diff < 0) {
		overall_diff *= -1;
	}
	printf("Final difference: %li ms\n", overall_diff);
	if (overall_diff >= 100) {
		printf("Compression detected\n");
	} else {
		printf("No compression detected\n");
	}
 
	return 0;	// Success
	
}
